services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
    # depends_on:
    #   - db

  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: openemr
  #     MYSQL_USER: mohit
  #     MYSQL_PASSWORD: mohit

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #   depends_on:
  #     - db

# volumes:
#   db_data:
